### ISSUE TITLE
Default indicators not shown on startup

### ISSUE THREAD

**Issue by lindyhoptrader** [team172011/TAcharting#18]
I'm running on a Mac, and when I launch the program the default MACD indicators setup in StartProgram.java don't show up.  I have to go into indicators menu and select them again.  Any idea why?  I know they're being created just not showing on the chart.

**Comment by team172011** [comment]
If I have understand you right, this is the expected behaviour. Default Indicators are not shown after program start, but it should be possible to select them from the menu.

**Comment by lindyhoptrader** [comment]
Then is there a function I could call to have an indicator always load on startup?  Or a way to save the chart configuration so that previously configured indicators reload on startup?

**Comment by team172011** [comment]
At the moment the TaChart class sets a listener on the IndicatorBox. To plot indicators automatically you have to add them to the indicator box after the listener has been set in constructor of TaChart. I am also working on a different approach in the d3 branch that will be merged soon
